owner: sun0wei
repo: sunwei-status

sites:
  - name: Blog
    url: https://blog.sunwei.online
  - name: Qexo
    url: https://qexo.sunwei.online
  - name: Website
    url: https://www.sunwei.online

status-website:
  cname: status.sunwei.online
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sunwei Status
  introTitle: "网站运行状态"
  introMessage: "这里显示网站在线状态、响应时间和历史可用率。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
